# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s = "Hi there Sam!"
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers.".format(planet, diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 

---
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)


*   List item

> Indented block


*   List item


## 4.2 Create an array of 10 fives?


In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arange(20,36)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [1]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a,b


(array([1, 2, 3]), array([4, 5, 6]))

# Pandas

8. Create a dataframe with 3 rows and 2 columns

In [ ]:
data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
df


Name  Age
0   tom   10
1  nick   15
2  juli   14

In [ ]:
import pandas as pd


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:

from datetime import timedelta, date

def daterange(date1, date2):
    for n in range(int ((date2 - date1).days)+1):
        yield date1 + timedelta

start_dt = date(2023, 1, 1)
end_dt = date(2023, 1, 10)
for dt in daterange(start_dt, end_dt):
    print(dt.strftime("%Y-%m-%d"))

TypeError: ignored

`10. Create 2D list to DataFrame`

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:

import pandas as pd
list = [[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df= pd.DataFrame(list,columns=['tag','char','number'])
print(df)

   tag char  number
0    1  aaa      22
1    2  bbb      25
2    3  ccc      24


In [ ]:

import pandas as pd
list = [[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df= pd.DataFrame(list,columns=['tag','char','number'])
print(df)

   tag char  number
0    1  aaa      22
1    2  bbb      25
2    3  ccc      24
